FROM node:18.15-alpine AS builder

WORKDIR /bidders

COPY package*.json tsconfig*.json nest-cli.json ./
COPY apps/api ./apps/api
COPY libs ./libs
COPY mysql-migrations ./mysql-migrations

RUN npm install
RUN npm run build

FROM node:18.15-alpine

WORKDIR /bidders

COPY --from=builder /bidders/. .

EXPOSE 4000

CMD ["npm", "run", "start:dev"]