FROM node:18.15-alpine AS builder

WORKDIR /bidders

COPY package*.json tsconfig*.json nest-cli.json ./
COPY apps/api ./apps/api
COPY libs ./libs

RUN npm install
RUN npm run build

FROM node:18.15-alpine

WORKDIR /bidders

COPY --from=builder /bidders/package*.json ./
COPY --from=builder /bidders/node_modules ./node_modules
COPY --from=builder /bidders/dist ./dist

EXPOSE 4000

CMD ["npm", "run", "start:prod"]