version: '3'
services:
    redis:
        image: redis:7.2.3-alpine
        restart: always
        container_name: redis
        ports:
            - ${REDIS_BINDING_PORT}:${REDIS_PORT} # 바인딩할 포트:내부 포트
        volumes:
            - ./db/redis/data:/data
            - ./db/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    mysql:
        image: mysql:8.0
        restart: always # 컨테이너 실행시 재시작
        container_name: mysql
        ports:
            - ${MYSQL_BINDING_PORT}:${MYSQL_PORT}
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - TZ=${TZ}
        volumes:
            - ./db/mysql/data:/var/lib/mysql
