### Sign in
# @name signinRequest
POST http://localhost:4000/user/signin
Content-Type: application/json

{
    "email": "test@bidders.com",
    "password": "1234"
}


###
@atk = {{signinRequest.response.body.atk}}
@rtk = {{signinRequest.response.body.rtk}}
###


### Create auction item
# @name createRequest
POST http://localhost:4000/auction/item
Authorization: Bearer {{atk}}
Content-Type: application/json

{
  "c_code": "0000",
  "title": "경매 등록 상품 제목",
  "content": "상품 내용 상세",
  "image": "https://auction-item.image.url",
  "start_datetime": "2024-02-25 15:00:00",
  "end_datetime": "2024-02-28 22:00:00",
  "start_price": 10000
}


###
@id = {{createRequest.response.body.id}}
###


### Auction item list
GET http://localhost:4000/auction/items


### Get auction item
GET http://localhost:4000/auction/item/{{id}}


### Update my auction item
PUT http://localhost:4000/auction/item/{{id}}
Authorization: Bearer {{atk}}
Content-Type: application/json

{
  "c_code": "0000",
  "title": "경매 등록 상품 제목 수정",
  "content": "상품 내용 상세 수정",
  "image": "https://auction-item.image.url",
  "start_datetime": "2023-12-12 15:00:00",
  "end_datetime": "2023-12-15 23:00:00",
  "start_price": 20000
}


### Update auction item status
PATCH http://localhost:4000/auction/item/{{id}}/status


### Update auction item likes
PATCH http://localhost:4000/auction/item/{{id}}/likes
Authorization: Bearer {{atk}}

###
@code = 0000
@minPrice = 10000
@maxPrice = 30000
###


### Search auction items
GET http://localhost:4000/auction/items/search

###
GET http://localhost:4000/auction/items/search?c_code={{code}}

###
GET http://localhost:4000/auction/items/search?c_code={{code}}&minPrice={{minPrice}}

###
GET http://localhost:4000/auction/items/search?c_code={{code}}&maxPrice={{maxPrice}}

###
GET http://localhost:4000/auction/items/search?minPrice={{minPrice}}

###
GET http://localhost:4000/auction/items/search?maxPrice={{maxPrice}}

###
GET http://localhost:4000/auction/items/search?minPrice={{minPrice}}&maxPrice={{maxPrice}}

###
GET http://localhost:4000/auction/items/search?c_code={{code}}&minPrice={{minPrice}}&maxPrice={{maxPrice}}
